use cudarc::driver::{CudaContext, DriverError, LaunchConfig, PushKernelArg};
use cudarc::nvrtc::Ptx;

pub fn execute_wiener_pipeline(data: &[f32]) -> Result<Vec<f32>, DriverError> {
    // 1. Initialize the GPU using CudaContext
    let ctx = CudaContext::new(0)?;

    // 2. Load the PTX kernel generated by our build.rs
    let ptx_bytes = include_bytes!(concat!(env!("OUT_DIR"), "/wiener.ptx"));
    
    // In cudarc 0.19.4 we use Ptx to wrap the raw bytes.
    // We use .into() so Rust automatically converts the Vec<u8> to Ptx.
    let module = ctx.load_module(ptx_bytes.to_vec().into())?;
    
    // 3. Retrieve the kernel function
    let f = module.get_fn("wiener_dummy").unwrap();

    let num_elements = data.len();
    let stream = ctx.default_stream();

    // 4. clone_htod: Allocates memory on the GPU and copies the data in a single step
    let mut d_in = stream.clone_htod(data)?;
    let mut d_out = stream.alloc_zeros::<f32>(num_elements)?;

    // 5. Configure the Kernel grid (Grid / Block)
    let threads_per_block = 256;
    let blocks = (num_elements as u32 + threads_per_block - 1) / threads_per_block;
    let cfg = LaunchConfig {
        grid_dim: (blocks, 1, 1),
        block_dim: (threads_per_block, 1, 1),
        shared_mem_bytes: 0,
    };

    // 6. Launch the kernel with the modern API using the stream builder
    // Thanks to the PushKernelArg import, .arg() works seamlessly.
    unsafe { stream.launch_builder(&f).arg(&mut d_out).arg(&d_in).arg(num_elements as i32).launch(cfg) }?;

    // 7. clone_dtoh: Copies the result back (Device -> Host) safely
    let result = stream.clone_dtoh(&d_out)?;

    Ok(result)
}
