use cudarc::driver::{CudaContext, DriverError, LaunchConfig, PushKernelArg};
use cudarc::nvrtc::Ptx;

pub fn execute_wiener_pipeline(data: &[f32]) -> Result<Vec<f32>, DriverError> {
    // 1. Initialize the GPU using CudaContext
    let ctx = CudaContext::new(0)?;

    // 2. Load the PTX kernel generated by our build.rs
    // We use include_str! because PTX files are plain text, 
    // and Ptx automatically implements From<&str>.
    let ptx_src = include_str!(concat!(env!("OUT_DIR"), "/wiener.ptx"));
    let module = ctx.load_module(Ptx::from(ptx_src))?;
    
    // 3. Retrieve the kernel function using the modern load_function API
    let f = module.load_function("wiener_dummy").unwrap();

    let num_elements = data.len();
    
    // NOTE: We bind the scalar to a variable because cudarc requires 
    // all kernel arguments to be passed by reference (&T).
    let n_i32 = num_elements as i32; 
    
    let stream = ctx.default_stream();

    // 4. clone_htod: Allocates memory on the GPU and copies the data in a single step
    let mut d_in = stream.clone_htod(data)?;
    let mut d_out = stream.alloc_zeros::<f32>(num_elements)?;

    // 5. Configure the Kernel grid (Grid / Block)
    let threads_per_block = 256;
    let blocks = (num_elements as u32 + threads_per_block - 1) / threads_per_block;
    let cfg = LaunchConfig {
        grid_dim: (blocks, 1, 1),
        block_dim: (threads_per_block, 1, 1),
        shared_mem_bytes: 0,
    };

    // 6. Launch the kernel with the modern API using the stream builder.
    // We pass &mut for outputs, and & for inputs/scalars.
    unsafe { 
        stream.launch_builder(&f)
            .arg(&mut d_out)
            .arg(&d_in)
            .arg(&n_i32)
            .launch(cfg) 
    }?;

    // 7. clone_dtoh: Copies the result back (Device -> Host) safely
    let result = stream.clone_dtoh(&d_out)?;

    Ok(result)
}
